### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by stanlysamuel**
Hi I created the Navbar without any dropdowns. (I assume that was asked only)
One bug: Not able to get the contents vertical aligned to middle.
Second bug: the inner container is not taking the height of the main div.

image

### CODE REVIEW

**Comment by amite** [comment]
@stanlysamuel - can you post a screenshot for visual issues like these?

**Comment by amite** [comment]
@stanlysamuel looks like you missed out on some css:

```css
.navbar-brand {
  padding: 0;
  line-height: 100px;
  height: 100px;
}

.logo-navbar .nav > li > a {
  padding-top: 38px;
  padding-bottom: 38px;
  line-height: 24px;
}
.logo-navbar .nav > li > a:before {
  margin-bottom: -21px;
}
.logo-navbar .nav > li.active > a:before, .logo-navbar .nav > li > a:hover:before, .logo-navbar .nav > li.current-page-parent > a:before, .logo-navbar .nav > li.current-menu-parent > a:before, .logo-navbar .nav > li.current-page-ancestor > a:before, .logo-navbar .nav > li.current-menu-ancestor > a:before {
  opacity: 1;
  margin-bottom: -19px;
}
```

This should get you half way there:

screen shot 2015-03-11 at 9 39 55 pm

**Comment by amite** [comment]
Also add an `About Us` and `Contact Us` link

**Comment by stanlysamuel** [comment]
Done!

Two bugs remain:
1) Navbar not responsive.
2) After clicking any link other than About Us, 'About us' link and the selected link (in the image, Business Research) both are active as shown in the image.

image

**Comment by amite** [comment]
@stanlysamuel I need you to file these as separate bugs that I can track and close. I am fine with mentioning them in pull requests for now but I need them as two different tickets with screenshots

**Comment by stanlysamuel** [comment]
@amite  you mean issues right?

**Comment by amite** [comment]
Yes I mean issues

**Pull request merged**
